export const ref = {
  palette: {
    blue900: "var(--ref-palette-blue900)",
    blue800: "var(--ref-palette-blue800)",
    blue700: "var(--ref-palette-blue700)",
    blue600: "var(--ref-palette-blue600)",
    blue500: "var(--ref-palette-blue500)",
    blue400: "var(--ref-palette-blue400)",
    blue300: "var(--ref-palette-blue300)",
    blue200: "var(--ref-palette-blue200)",
    blue100: "var(--ref-palette-blue100)",
    blue50: "var(--ref-palette-blue50)",
    green900: "var(--ref-palette-green900)",
    green800: "var(--ref-palette-green800)",
    green700: "var(--ref-palette-green700)",
    green600: "var(--ref-palette-green600)",
    green500: "var(--ref-palette-green500)",
    green400: "var(--ref-palette-green400)",
    green300: "var(--ref-palette-green300)",
    green200: "var(--ref-palette-green200)",
    green100: "var(--ref-palette-green100)",
    green50: "var(--ref-palette-green50)",
    yellow900: "var(--ref-palette-yellow900)",
    yellow800: "var(--ref-palette-yellow800)",
    yellow700: "var(--ref-palette-yellow700)",
    yellow600: "var(--ref-palette-yellow600)",
    yellow500: "var(--ref-palette-yellow500)",
    yellow400: "var(--ref-palette-yellow400)",
    yellow300: "var(--ref-palette-yellow300)",
    yellow200: "var(--ref-palette-yellow200)",
    yellow100: "var(--ref-palette-yellow100)",
    yellow50: "var(--ref-palette-yellow50)",
    orange900: "var(--ref-palette-orange900)",
    orange800: "var(--ref-palette-orange800)",
    orange700: "var(--ref-palette-orange700)",
    orange600: "var(--ref-palette-orange600)",
    orange500: "var(--ref-palette-orange500)",
    orange400: "var(--ref-palette-orange400)",
    orange300: "var(--ref-palette-orange300)",
    orange200: "var(--ref-palette-orange200)",
    orange100: "var(--ref-palette-orange100)",
    orange50: "var(--ref-palette-orange50)",
    red900: "var(--ref-palette-red900)",
    red800: "var(--ref-palette-red800)",
    red700: "var(--ref-palette-red700)",
    red600: "var(--ref-palette-red600)",
    red500: "var(--ref-palette-red500)",
    red400: "var(--ref-palette-red400)",
    red300: "var(--ref-palette-red300)",
    red200: "var(--ref-palette-red200)",
    red100: "var(--ref-palette-red100)",
    red50: "var(--ref-palette-red50)",
    gray900: "var(--ref-palette-gray900)",
    gray800: "var(--ref-palette-gray800)",
    gray700: "var(--ref-palette-gray700)",
    gray600: "var(--ref-palette-gray600)",
    gray500: "var(--ref-palette-gray500)",
    gray400: "var(--ref-palette-gray400)",
    gray300: "var(--ref-palette-gray300)",
    gray200: "var(--ref-palette-gray200)",
    gray100: "var(--ref-palette-gray100)",
    gray50: "var(--ref-palette-gray50)",
    black: "var(--ref-palette-black)",
    white: "var(--ref-palette-white)",
  },
};

export const sys = {
  color: {
    container: {
      primary: {
        fill: {
          light1: "var(--sys-color-container-primary-fill-light1)",
          light2: "var(--sys-color-container-primary-fill-light2)",
          dark1: "var(--sys-color-container-primary-fill-dark1)",
          dark2: "var(--sys-color-container-primary-fill-dark2)",
        },
        border: {
          light1: "var(--sys-color-container-primary-border-light1)",
          light2: "var(--sys-color-container-primary-border-light2)",
          dark1: "var(--sys-color-container-primary-border-dark1)",
          dark2: "var(--sys-color-container-primary-border-dark2)",
        },
      },
      secondary: {
        fill: {
          light1: "var(--sys-color-container-secondary-fill-light1)",
          light2: "var(--sys-color-container-secondary-fill-light2)",
          dark1: "var(--sys-color-container-secondary-fill-dark1)",
          dark2: "var(--sys-color-container-secondary-fill-dark2)",
        },
        border: {
          light1: "var(--sys-color-container-secondary-border-light1)",
          light2: "var(--sys-color-container-secondary-border-light2)",
          dark1: "var(--sys-color-container-secondary-border-dark1)",
          dark2: "var(--sys-color-container-secondary-border-dark2)",
        },
      },
      tertiary: {
        fill: {
          light1: "var(--sys-color-container-tertiary-fill-light1)",
          light2: "var(--sys-color-container-tertiary-fill-light2)",
          dark1: "var(--sys-color-container-tertiary-fill-dark1)",
          dark2: "var(--sys-color-container-tertiary-fill-dark2)",
        },
        border: {
          light1: "var(--sys-color-container-tertiary-border-light1)",
          light2: "var(--sys-color-container-tertiary-border-light2)",
          dark1: "var(--sys-color-container-tertiary-border-dark1)",
          dark2: "var(--sys-color-container-tertiary-border-dark2)",
        },
      },
      success: {
        fill: {
          light1: "var(--sys-color-container-success-fill-light1)",
          light2: "var(--sys-color-container-success-fill-light2)",
          dark1: "var(--sys-color-container-success-fill-dark1)",
          dark2: "var(--sys-color-container-success-fill-dark2)",
        },
        border: {
          light1: "var(--sys-color-container-success-border-light1)",
          light2: "var(--sys-color-container-success-border-light2)",
          dark1: "var(--sys-color-container-success-border-dark1)",
          dark2: "var(--sys-color-container-success-border-dark2)",
        },
      },
      info: {
        fill: {
          light1: "var(--sys-color-container-info-fill-light1)",
          light2: "var(--sys-color-container-info-fill-light2)",
          dark1: "var(--sys-color-container-info-fill-dark1)",
          dark2: "var(--sys-color-container-info-fill-dark2)",
        },
        border: {
          light1: "var(--sys-color-container-info-border-light1)",
          light2: "var(--sys-color-container-info-border-light2)",
          dark1: "var(--sys-color-container-info-border-dark1)",
          dark2: "var(--sys-color-container-info-border-dark2)",
        },
      },
      warning: {
        fill: {
          light1: "var(--sys-color-container-warning-fill-light1)",
          light2: "var(--sys-color-container-warning-fill-light2)",
          dark1: "var(--sys-color-container-warning-fill-dark1)",
          dark2: "var(--sys-color-container-warning-fill-dark2)",
        },
        border: {
          light1: "var(--sys-color-container-warning-border-light1)",
          light2: "var(--sys-color-container-warning-border-light2)",
          dark1: "var(--sys-color-container-warning-border-dark1)",
          dark2: "var(--sys-color-container-warning-border-dark2)",
        },
      },
      danger: {
        fill: {
          light1: "var(--sys-color-container-danger-fill-light1)",
          light2: "var(--sys-color-container-danger-fill-light2)",
          dark1: "var(--sys-color-container-danger-fill-dark1)",
          dark2: "var(--sys-color-container-danger-fill-dark2)",
        },
        border: {
          light1: "var(--sys-color-container-danger-border-light1)",
          light2: "var(--sys-color-container-danger-border-light2)",
          dark1: "var(--sys-color-container-danger-border-dark1)",
          dark2: "var(--sys-color-container-danger-border-dark2)",
        },
      },
      base: {
        fill: {
          light1: "var(--sys-color-container-base-fill-light1)",
          light2: "var(--sys-color-container-base-fill-light2)",
          dark1: "var(--sys-color-container-base-fill-dark1)",
          dark2: "var(--sys-color-container-base-fill-dark2)",
        },
        border: {
          light1: "var(--sys-color-container-base-border-light1)",
          light2: "var(--sys-color-container-base-border-light2)",
          dark1: "var(--sys-color-container-base-border-dark1)",
          dark2: "var(--sys-color-container-base-border-dark2)",
        },
      },
    },
    text: {
      other: {
        black: "var(--sys-color-text-other-black)",
        white: "var(--sys-color-text-other-white)",
      },
      primary: {
        dark2: "var(--sys-color-text-primary-dark2)",
        dark1: "var(--sys-color-text-primary-dark1)",
        light2: "var(--sys-color-text-primary-light2)",
        light1: "var(--sys-color-text-primary-light1)",
      },
      secondary: {
        dark2: "var(--sys-color-text-secondary-dark2)",
        dark1: "var(--sys-color-text-secondary-dark1)",
        light2: "var(--sys-color-text-secondary-light2)",
        light1: "var(--sys-color-text-secondary-light1)",
      },
      tertiary: {
        dark2: "var(--sys-color-text-tertiary-dark2)",
        dark1: "var(--sys-color-text-tertiary-dark1)",
        light2: "var(--sys-color-text-tertiary-light2)",
        light1: "var(--sys-color-text-tertiary-light1)",
      },
      success: {
        dark2: "var(--sys-color-text-success-dark2)",
        dark1: "var(--sys-color-text-success-dark1)",
        light2: "var(--sys-color-text-success-light2)",
        light1: "var(--sys-color-text-success-light1)",
      },
      info: {
        dark2: "var(--sys-color-text-info-dark2)",
        dark1: "var(--sys-color-text-info-dark1)",
        light2: "var(--sys-color-text-info-light2)",
        light1: "var(--sys-color-text-info-light1)",
      },
      warning: {
        dark2: "var(--sys-color-text-warning-dark2)",
        dark1: "var(--sys-color-text-warning-dark1)",
        light2: "var(--sys-color-text-warning-light2)",
        light1: "var(--sys-color-text-warning-light1)",
      },
      danger: {
        dark2: "var(--sys-color-text-danger-dark2)",
        dark1: "var(--sys-color-text-danger-dark1)",
        light2: "var(--sys-color-text-danger-light2)",
        light1: "var(--sys-color-text-danger-light1)",
      },
      base: {
        dark2: "var(--sys-color-text-base-dark2)",
        dark1: "var(--sys-color-text-base-dark1)",
        light2: "var(--sys-color-text-base-light2)",
        light1: "var(--sys-color-text-base-light1)",
      },
    },
    icon: {
      other: {
        black: "var(--sys-color-icon-other-black)",
        white: "var(--sys-color-icon-other-white)",
      },
      primary: {
        dark2: "var(--sys-color-icon-primary-dark2)",
        dark1: "var(--sys-color-icon-primary-dark1)",
        light2: "var(--sys-color-icon-primary-light2)",
        light1: "var(--sys-color-icon-primary-light1)",
      },
      secondary: {
        dark2: "var(--sys-color-icon-secondary-dark2)",
        dark1: "var(--sys-color-icon-secondary-dark1)",
        light2: "var(--sys-color-icon-secondary-light2)",
        light1: "var(--sys-color-icon-secondary-light1)",
      },
      tertiary: {
        dark2: "var(--sys-color-icon-tertiary-dark2)",
        dark1: "var(--sys-color-icon-tertiary-dark1)",
        light2: "var(--sys-color-icon-tertiary-light2)",
        light1: "var(--sys-color-icon-tertiary-light1)",
      },
      success: {
        dark2: "var(--sys-color-icon-success-dark2)",
        dark1: "var(--sys-color-icon-success-dark1)",
        light2: "var(--sys-color-icon-success-light2)",
        light1: "var(--sys-color-icon-success-light1)",
      },
      info: {
        dark2: "var(--sys-color-icon-info-dark2)",
        dark1: "var(--sys-color-icon-info-dark1)",
        light2: "var(--sys-color-icon-info-light2)",
        light1: "var(--sys-color-icon-info-light1)",
      },
      warning: {
        dark2: "var(--sys-color-icon-warning-dark2)",
        dark1: "var(--sys-color-icon-warning-dark1)",
        light2: "var(--sys-color-icon-warning-light2)",
        light1: "var(--sys-color-icon-warning-light1)",
      },
      danger: {
        dark2: "var(--sys-color-icon-danger-dark2)",
        dark1: "var(--sys-color-icon-danger-dark1)",
        light2: "var(--sys-color-icon-danger-light2)",
        light1: "var(--sys-color-icon-danger-light1)",
      },
      base: {
        dark2: "var(--sys-color-icon-base-dark2)",
        dark1: "var(--sys-color-icon-base-dark1)",
        light2: "var(--sys-color-icon-base-light2)",
        light1: "var(--sys-color-icon-base-light1)",
      },
    },
    bg: {
      white: "var(--sys-color-bg-white)",
      gray: "var(--sys-color-bg-gray)",
    },
    stateLayer: {
      op1: "var(--sys-color-state-layer-op1)",
      op2: "var(--sys-color-state-layer-op2)",
      op3: "var(--sys-color-state-layer-op3)",
    },
    other: {
      backdrop: "var(--sys-color-other-backdrop)",
    },
  },
};
